version: "3.3" # version of compose format

services:
  landing-service:
    build: ./landing # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 6090:6090 # host:container
    networks:
      sample:
        aliases:
          - landing-service
  # Add more services below
  addition:
    build: ./addition
    ports:
      - 6089:6089
    networks:
      sample:
        aliases:
          - addition
  bitwise_or:
    build: ./bitwise_or
    ports:
      - 6085:6085
    networks:
      sample:
        aliases:
          - bitwise_or
  maximum:
    build: ./maximum
    ports:
      - 6084:6084
    networks:
      sample:
        aliases:
          - maximum 
  divide:
    build: ./divide
    ports:
      - 6086:6086
    networks:
      sample:
        aliases:
          - divide
  multiply:
    build: ./multiply
    ports:
      - 6087:6087
    networks:
      sample:
        aliases:
          - multiply  
  minimum:
    build: ./minimum
    ports:
      - 6083:6083
    networks:
      sample:
        aliases:
          - minimum   
  average:
    build: ./average
    ports:
      - 6082:6082
    networks:
      sample:
        aliases:
          - average  
  exponential:
    build: ./exponential
    ports:
      - 6081:6081
    networks:
      sample:
        aliases:
          - exponential 
  minus:
    build: ./minus
    ports:
      - 6088:6088
    networks:
      sample:
        aliases:
          - minus
networks:
  sample:
